@file:Suppress("SpellCheckingInspection")

package com.arkhe.menu.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF4E5260)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF666A79)
val onPrimaryContainerLight = Color(0xFFE8EBFD)
val secondaryLight = Color(0xFF5D5E64)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDFDFE6)
val onSecondaryContainerLight = Color(0xFF616269)
val tertiaryLight = Color(0xFF5E4D5A)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF776572)
val onTertiaryContainerLight = Color(0xFFFDE5F4)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF8F9)
val onBackgroundLight = Color(0xFF1C1B1C)
val surfaceLight = Color(0xFFFCF8F9)
val onSurfaceLight = Color(0xFF1C1B1C)
val surfaceVariantLight = Color(0xFFE3E2E8)
val onSurfaceVariantLight = Color(0xFF46464C)
val outlineLight = Color(0xFF76777C)
val outlineVariantLight = Color(0xFFC6C6CC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313031)
val inverseOnSurfaceLight = Color(0xFFF3F0F1)
val inversePrimaryLight = Color(0xFFC2C6D7)
val surfaceDimLight = Color(0xFFDCD9DA)
val surfaceBrightLight = Color(0xFFFCF8F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F3F4)
val surfaceContainerLight = Color(0xFFF0EDEE)
val surfaceContainerHighLight = Color(0xFFEBE7E8)
val surfaceContainerHighestLight = Color(0xFFE5E2E3)

val primaryDark = Color(0xFFC2C6D7)
val onPrimaryDark = Color(0xFF2C303D)
val primaryContainerDark = Color(0xFF666A79)
val onPrimaryContainerDark = Color(0xFFE8EBFD)
val secondaryDark = Color(0xFFC6C6CD)
val onSecondaryDark = Color(0xFF2F3036)
val secondaryContainerDark = Color(0xFF45464D)
val onSecondaryContainerDark = Color(0xFFB5B4BC)
val tertiaryDark = Color(0xFFD6C0CF)
val onTertiaryDark = Color(0xFF3B2C37)
val tertiaryContainerDark = Color(0xFF776572)
val onTertiaryContainerDark = Color(0xFFFDE5F4)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131314)
val onBackgroundDark = Color(0xFFE5E2E3)
val surfaceDark = Color(0xFF131314)
val onSurfaceDark = Color(0xFFE5E2E3)
val surfaceVariantDark = Color(0xFF46464C)
val onSurfaceVariantDark = Color(0xFFC6C6CC)
val outlineDark = Color(0xFF909096)
val outlineVariantDark = Color(0xFF46464C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E2E3)
val inverseOnSurfaceDark = Color(0xFF313031)
val inversePrimaryDark = Color(0xFF5A5E6D)
val surfaceDimDark = Color(0xFF131314)
val surfaceBrightDark = Color(0xFF3A393A)
val surfaceContainerLowestDark = Color(0xFF0E0E0F)
val surfaceContainerLowDark = Color(0xFF1C1B1C)
val surfaceContainerDark = Color(0xFF201F20)
val surfaceContainerHighDark = Color(0xFF2A2A2B)
val surfaceContainerHighestDark = Color(0xFF353436)